version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/frontend/"
    assignees:
      - awfixer
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "/backend/"
    assignees:
      - awfixer
    schedule:
      interval: "daily"
  - package-ecosystem: "pip"
    directory: "/setup/"
    assignees:
      - awfixer
    schedule:
      interval: "daily"
